lane :certs do
	match(type: "development", readonly: true)
	match(type: "adhoc", readonly: true)
	match(type: "appstore", readonly: true)
end

lane :dev_certs_force do
	match(type: "development", force: true)
end
